version: "3.3"

services:
  dspacedb:
    image: dspace/dspace-postgres-pgcrypto
    environment:
      - PGDATA=/pgdata
    volumes:
      - pgdata:/pgdata
    networks:
      - dspacenet
    tty: true
    stdin_open: true

  so_edu_mu:
    build:
      ../../dockerfiles/so_edu_mu
    image: so_edu_mu:0.1
    environment:
      - DSPACE_INSTALL=/dspace
    ports:
      - 8080:8080
    volumes:
      - "assetstore:/dspace/assetstore"
      - "solr:/dspace/solr"
      # Uncomment the following to enable Mirage2 (DSpace 5x or 6x only)
      - "../../add-ons/mirage2/xmlui.xconf:/dspace/config/xmlui.xconf"
    networks:
      - dspacenet
    depends_on:
      - dspacedb
    tty: true
    stdin_open: true
    environment:
      - VIRTUAL_HOST=repository.mu.edu.so
      - VIRTUAL_PORT=8080
      - LETSENCRYPT_EMAIL=devops@ubuntunet.net
      - LETSENCRYPT_HOST=repository.mu.edu.so

  nginx-proxy:
    image: jwilder/nginx-proxy:0.7.0
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./certs:/etc/nginx/certs:ro
      - ./htpasswd:/etc/nginx/htpasswd
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: unless-stopped

  nginx-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion:v1.9
    volumes:
      - ./certs:/etc/nginx/certs:rw
      - ./htpasswd:/etc/nginx/htpasswd
      - nginx-conf:/etc/nginx/conf.d
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped

volumes:
  nginx-conf:
  nginx-vhost:
  nginx-html:
  pgdata:
  assetstore:
  solr:

networks:
  dspacenet:
